name: mp_docvqa
channels:
  - defaults

dependencies:
  - python==3.8
  - protobuf<=3.20
  - pip
  - tqdm
  - numpy
  - pillow
  - pip:
    - onnx
    - wandb==0.16.6
    - onnxruntime
    - ipykernel
    - sentencepiece
    - datasets transformers[sentencepiece]
    - transformers==4.26.1
    - editdistance
    # - git+https://github.com/openai/CLIP.git

# conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
