name: mp_docvqa
channels:
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python==3.8
  - protobuf<=3.20
  - pip
  - tqdm
  - numpy
  - pillow
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - faiss-gpu=1.8.0
  - pip:
    - onnx
    - wandb==0.16.6
    - onnxruntime
    - ipykernel
    - sentencepiece
    - datasets transformers[sentencepiece]
    - transformers==4.26.1
    - editdistance
    - langchain==0.2.16
    - langchain-community==0.2.17
    - langchain-huggingface==0.0.3

# conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
