dataset_name: Infographics
json_dir: /data/users/elopez/infographics/qas  # /imdb/collection/imdb_train.npy
ocr_dir: /data/users/elopez/infographics/ocr
images_dir: /data/users/elopez/infographics/images
page_retrieval: Concat  # Oracle / Concat / Logits / Maxconf / Anyconf / MaxConfPage / AnyConfPage / MajorPage / WeightMajorPage / Custom (HiVT5 only)
