dataset_name: MP-DocVQA
imdb_dir: /data3fast/users/elopez/data/mpdocvqa_imdb  # /imdb/collection/imdb_train.npy
images_dir: /data3fast/users/elopez/data/images
layouts_dir: /data3fast/users/elopez/data/
page_retrieval: Concat  # Oracle / Concat / Logits / Maxconf / Anyconf / MaxConfPage / AnyConfPage / MajorPage / WeightMajorPage / Custom (HiVT5 only)
