dataset_name: MP-DocVQA
imdb_dir: /data3fast/users/elopez/data/mpdocvqa_imdb  # /imdb/collection/imdb_train.npy
images_dir: /data3fast/users/elopez/data/images
page_retrieval: Concat  # Oracle / Concat / Logits / Maxconf / Custom (for Hierarchical methods (Hi-LayoutLMv3, Hi-LT5, Hi-VT5)
