model:
  model: RAGVT5
  add_sep_token: False
  # model_weights: /data3fast/users/elopez/checkpoints/ragvt5_concat_mp-docvqa_train_generator/best.ckpt

data:
  dataset: MP-DocVQA
  page_retrieval: Concat
  batch_size: 40
  # layout_batch_size: 8

retrieval:
  chunk_num: [10, 10, 10, 20, 20, 30, 20, 20, 20, 30]
  chunk_size: 60
  chunk_size_tol: 0.2
  overlap: 10
  include_surroundings: 0
  embed_model: BGE # BGE, VT5, BGE-M3, BGE-reranker
  embed_weights: /data3fast/users/elopez/models/bge-finetuned-2/checkpoint-820
  reranker_weights: BAAI/bge-reranker-base
  rerank_filter_tresh: [0, 0, 0, 0, 0, 0, 0.2, 0.4, 0.6, 0.6]
  rerank_max_chunk_num: [1, 3, 5, 5, 10, 10, 10, 10, 10, 10]
  rerank_min_chunk_num: 1
  
# layout_model:
#   layout_model: DIT # DIT, YOLO
#   layout_model_weights: cmarkea/dit-base-layout-detection
#   use_layout_labels: Text # Default, Embed, Text
#   use_precomputed_layouts: True
#   precomputed_layouts_path: /data3fast/users/elopez/data/images_layouts_dit_s2_spa.npz
#   layout_embedding_scale: 10.0
#   layout_loss_weight: 1.0
#   cluster_layouts: True
#   cluster_mode: spatial # spatial, spatial+semantic
#   calculate_n_clusters: best # heuristic, best

runtime:
  visible_devices: [5, 6, 7, 8, 9]
  save_folder: 15-reranker
  save_name_append: ["10_0_1", "10_0_3", "10_0_5", "20_0_5", "20_0_10", "30_0_10", "20_02_10", "20_04_10", "20_06_10", "30_06_10"]
  val_size: 1.0
  log_wandb: True
  log_media_interval: 10
  return_scores_by_sample: True
  return_answers: True
  save_results: False
  save_continuously: True
  compute_stats: False
  compute_stats_examples: False
  n_stats_examples: 5
