model:
  model: RAGVT5
  add_sep_token: False
  # model_weights: /data3fast/users/elopez/checkpoints/ragvt5_concat_mp-docvqa_train_generator/best.ckpt

data:
  dataset: Infographics
  page_retrieval: [Concat, Oracle]
  batch_size: 30
  # layout_batch_size: 8

retrieval:
  chunk_num: 20
  chunk_size: 60
  chunk_size_tol: 0.2
  overlap: 10
  include_surroundings: 0
  embed_model: BGE # BGE, VT5
  reranker_model: BGE
  embed_weights: /data3fast/users/elopez/models/bge-finetuned/checkpoint-820
  reranker_weights: BAAI/bge-reranker-v2-m3
  reorder_chunks: False
  rerank_filter_tresh: 0
  rerank_max_chunk_num: 10
  rerank_min_chunk_num: 1
  
# layout_model:
#   layout_model: DIT # DIT, YOLO
#   layout_model_weights: cmarkea/dit-base-layout-detection
#   use_layout_labels: Text # Default, Embed, Text
#   use_precomputed_layouts: True
#   precomputed_layouts_path: /data3fast/users/elopez/data/images_layouts_dit_s2_spa.npz
#   layout_embedding_scale: 10.0
#   layout_loss_weight: 1.0
#   cluster_layouts: True
#   cluster_mode: spatial # spatial, spatial+semantic
#   calculate_n_clusters: best # heuristic, best

runtime:
  visible_devices: [8, 9]
  save_folder: 17-infographics
  save_name_append: Infographics
  val_size: 1.0
  log_wandb: True
  log_media_interval: 10
  return_scores_by_sample: True
  return_answers: True
  save_results: False
  save_continuously: True
  compute_stats: False
  compute_stats_examples: False
  n_stats_examples: 5
