model:
  model: RAGVT5
  embed_model: BGE # BGE, VT5, BGE-M3, BGE-reranker
  layout_model: YOLO
  add_sep_token: False
  model_weights: /data3fast/users/elopez/checkpoints/ragvt5_concat_mp-docvqa_train_generator/best.ckpt

data:
  dataset: MP-DocVQA
  page_retrieval: [Oracle, Concat, AnyConf]
  batch_size: [50, 40, 32]
  layout_batch_size: 8

retrieval:
  chunk_num: 10
  chunk_size: 60
  chunk_size_tol: 0.2
  overlap: 10
  include_surroundings: 0
  embed_weights: /data3fast/users/elopez/models/bge-finetuned-2/checkpoint-820
  
layout_model:
  layout_model_weights: juliozhao/DocLayout-YOLO-DocStructBench
  use_layout_labels: False
  use_precomputed_layouts: True
  layout_embedding_scale: 1.0
  layout_loss_weight: 1.0

runtime:
  visible_devices: [1, 2, 3]
  save_folder: 10-yolo_layout
  save_name_append: yolo_no_labels
  val_size: 1.0
  log_wandb: True
  log_media_interval: 10
  return_scores_by_sample: True
  return_answers: True
  save_results: False
  save_continuously: True
  compute_stats: False
  compute_stats_examples: False
  n_stats_examples: 5
