save_dir: save/
model_name: RAGVT5
model_weights: rubentito/vt5-base-spdocvqa
cache_dir: /data3fast/users/elopez/models
max_source_length: 512
device: cuda
data_parallel: False

training_parameters:
  lr: 2e-4
  batch_size: 4
  train_epochs: 10
  warmup_iterations: 1000

visual_module:
  model: 'dit'  # 'vit' / 'dit'
  finetune: false
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'

